Repository Elice-Back-end/KETCH-CATCH, pull requests merged in 2024-11, with the labels that each got.

#43 게임 종료 후 기능 구현
  src/game/game.gateway.ts
  src/game/game.module.ts
  src/game/game.service.ts
  src/room/room.gateway.ts
  src/room/room.module.ts
  src/room/room.service.ts
Labels: 기능, 수정

#44 코드 수정
  src/main.ts
  src/room/room-user.service.ts
  src/room/room.service.ts
Labels: 수정

#47 🚚 점수 더하기 기능 구현
  src/game/game.gateway.ts
  src/game/game.service.ts
Labels: 기능

#48 🚚 다음라운드 기능 추가
  src/data/word.ts
  src/game/game.gateway.ts
  src/game/game.interface.ts
  src/game/game.service.ts
Labels: 기능

#49 🚚 게임종료 기능 구현
  src/game/game.gateway.ts
  src/game/game.service.ts
Labels: 기능

#50 🚚 게임 중 유저퇴장 기능 구현
  src/game/game.gateway.ts
  src/game/game.service.ts
Labels: 기능

#51 🔥 사진 파일 제거
  public/eyes/eyes1.svg
  public/eyes/eyes2.svg
  public/eyes/eyes3.svg
  public/eyes/eyes4.svg
  public/eyes/eyes5.svg
  public/eyes/eyes6.svg
  public/eyes/eyes7.svg
  public/eyes/eyes8.svg
  public/ghosts/ghost-error.svg
  public/ghosts/ghost-main.svg
  public/ghosts/ghost-mini.svg
  public/ghosts/ghost1.svg
  public/ghosts/ghost2.svg
  public/ghosts/ghost3.svg
  public/ghosts/ghost4.svg
  public/ghosts/ghost5.svg
  public/ghosts/ghost6.svg
  public/ghosts/ghost7.svg
  public/ghosts/ghost8.svg
Labels: 문서

#52 🔥코드 삭제
  src/data/room/room.interface.ts
  src/data/user/user.interface.ts
  src/room/dto/user.dto.ts
  src/room/room.service.ts
Labels: 수정

#53 코드 수정
  src/room/dto/room-setting.dto.ts
  src/room/room-user.service.ts
  src/room/room.controller.ts
Labels: 수정

#54 📝 next-round 수정
  src/game/game.gateway.ts
  src/game/game.service.ts
Labels: 수정

#56 🔥 필요없는 payload 데이터코드 삭제
  src/game/game.service.ts
Labels: 수정
